# Generated by Django 4.0.4 on 2022-05-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='emal',
            new_name='email',
        ),
    ]
